{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "guildMemberAdd",
    "content": null
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{if;{user.bot};==;false;{perset;lastmemberjoin;{user.mention}}}",
      "id": "5ebd35e48f44120026a7fc8a"
    }
  ],
  "formatVersion": "1.2"
}