{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": true,
    "quiet": true
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [
      "676445020470902804",
      "676445023251726337"
    ],
    "channels": [],
    "permissions": []
  },
  "trigger": {
    "type": "messageCreate",
    "content": "676445209562710026"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message":"{message.delete} {if;{message.content};!==;;{a!ae;--footer="UserID : {user.id}";--title="SUGGESTION";--description="{message.content}";--color="{user.color;true}";--thumbnail="{user.avatarURL}";--timestamp="true";--name="{user.username}"} {set;lastmessageID;{channel.lastMessageID}}{message.react;✅;{get;lastmessageID};{channel.id}} {message.react;➖;{get;lastmessageID};{channel.id}} {message.react;❌;{get;lastmessageID};{channel.id}};{user.send;<a:refuse:552815066932838403> Vous devez inclure un message !}}",
      "id": "5e4ec04d36c899002efd1a8f"
    }
  ],
  "formatVersion": "1.2"
}
